[package]
name = "base64"
version = "0.1.0"
authors = ["Niklas Buechner <niklas.buechner@viison.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
